export enum MediaType {
  PHOTO = "Photo",
  VIDEO = "Video",
  PHOTO_RAW = "PhotoRaw",
}

interface IExtensionTypes {
  [name: string]: string
}

export const MediaExtensionTypes: IExtensionTypes = {
  '.jpg': MediaType.PHOTO,
  '.jpeg': MediaType.PHOTO,
  '.png': MediaType.PHOTO,
  '.bmp': MediaType.PHOTO,
  '.webp': MediaType.PHOTO,
  '.tiff': MediaType.PHOTO,
  '.tif': MediaType.PHOTO,

  '.3fr': MediaType.PHOTO_RAW,
  '.3gp2': MediaType.PHOTO_RAW,
  '.3gpp': MediaType.PHOTO_RAW,
  '.arq': MediaType.PHOTO_RAW,
  '.arw': MediaType.PHOTO_RAW,
  '.bpg': MediaType.PHOTO_RAW,
  '.cr2': MediaType.PHOTO_RAW,
  '.cr3': MediaType.PHOTO_RAW,
  '.crm': MediaType.PHOTO_RAW,
  '.crw': MediaType.PHOTO_RAW,
  '.ciff': MediaType.PHOTO_RAW,
  '.cs1': MediaType.PHOTO_RAW,
  '.czi': MediaType.PHOTO_RAW,
  '.dcp': MediaType.PHOTO_RAW,
  '.dcr': MediaType.PHOTO_RAW,
  '.divx': MediaType.PHOTO_RAW,
  '.dng': MediaType.PHOTO_RAW,
  '.exif': MediaType.PHOTO_RAW,
  '.fff': MediaType.PHOTO_RAW,
  '.gif': MediaType.PHOTO_RAW,
  '.gpr': MediaType.PHOTO_RAW,
  '.hdr': MediaType.PHOTO_RAW,
  '.heic': MediaType.PHOTO_RAW,
  '.heif': MediaType.PHOTO_RAW,
  '.hif': MediaType.PHOTO_RAW,
  '.insp': MediaType.PHOTO_RAW,
  '.insv': MediaType.PHOTO_RAW,
  '.jp2': MediaType.PHOTO_RAW,
  '.jpf': MediaType.PHOTO_RAW,
  '.jpm': MediaType.PHOTO_RAW,
  '.jpx': MediaType.PHOTO_RAW,
  '.jpe': MediaType.PHOTO_RAW,
  '.k25': MediaType.PHOTO_RAW,
  '.kdc': MediaType.PHOTO_RAW,
  '.lif': MediaType.PHOTO_RAW,
  '.lnk': MediaType.PHOTO_RAW,
  '.m2ts': MediaType.PHOTO_RAW,
  '.mts': MediaType.PHOTO_RAW,
  '.m2t': MediaType.PHOTO_RAW,
  '.ts': MediaType.PHOTO_RAW,
  '.mef': MediaType.PHOTO_RAW,
  '.mka': MediaType.PHOTO_RAW,
  '.mkv': MediaType.PHOTO_RAW,
  '.mks': MediaType.PHOTO_RAW,
  '.m2v': MediaType.PHOTO_RAW,
  '.mrw': MediaType.PHOTO_RAW,
  '.nef': MediaType.PHOTO_RAW,
  '.nrw': MediaType.PHOTO_RAW,
  '.orf': MediaType.PHOTO_RAW,
  '.ori': MediaType.PHOTO_RAW,
  '.pef': MediaType.PHOTO_RAW,
  '.pmp': MediaType.PHOTO_RAW,
  '.jng': MediaType.PHOTO_RAW,
  '.mng': MediaType.PHOTO_RAW,
  '.raf': MediaType.PHOTO_RAW,
  '.raw': MediaType.PHOTO_RAW,
  '.rw2': MediaType.PHOTO_RAW,
  '.rwl': MediaType.PHOTO_RAW,
  '.sr2': MediaType.PHOTO_RAW,
  '.srf': MediaType.PHOTO_RAW,
  '.srw': MediaType.PHOTO_RAW,
  '.x3f': MediaType.PHOTO_RAW,

  '.mov': MediaType.VIDEO,
  '.mp4': MediaType.VIDEO,
  '.aa': MediaType.VIDEO,
  '.apng': MediaType.VIDEO,
  '.flv': MediaType.VIDEO,
  '.live_flv': MediaType.VIDEO,
  '.kux': MediaType.VIDEO,
  '.m4a': MediaType.VIDEO,
  '.3gp': MediaType.VIDEO,
  '.3g2': MediaType.VIDEO,
  '.mj2': MediaType.VIDEO,
  '.psp': MediaType.VIDEO,
  '.m4b': MediaType.VIDEO,
  '.ism': MediaType.VIDEO,
  '.ismv': MediaType.VIDEO,
  '.isma': MediaType.VIDEO,
  '.f4v': MediaType.VIDEO,
  '.webm': MediaType.VIDEO,
  '.avi': MediaType.VIDEO,
  '.mpeg': MediaType.VIDEO,
  '.mpg': MediaType.VIDEO,
};
